CREATE TABLE course_bookmark (
    course_bookmark_id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    course_id NUMBER NOT NULL,
    user_id NUMBER NOT NULL,
    created_at TIMESTAMP DEFAULT SYSTIMESTAMP NOT NULL,
    CONSTRAINT uq_course_bookmark UNIQUE (course_id, user_id),
    CONSTRAINT fk_course_bookmark_course FOREIGN KEY (course_id) REFERENCES course(course_id),
    CONSTRAINT fk_course_bookmark_user FOREIGN KEY (user_id) REFERENCES app_user(user_id)
);

CREATE INDEX idx_course_bookmark_user_created
    ON course_bookmark (user_id, created_at DESC);
